
"""
Given any initial natural number, consider the sequence of numbers generated by repeatedly following the rule:

divide by two if the number is even or
multiply by 3 and add 1 if the number is odd.

The Collatz conjecture states that this sequence always terminates at 1.
"""

import math

def Collatz_conjecture(n):
    time = 0
    list_number = []
    while n > 1:
        time += 1
        list_number.append(n)

        if (n % 2) == 0:
            n = n // 2
        elif (n % 2) != 0:
            n = n * 3 + 1
    
    list_number.append(1)
    print (max(list_number))
    print (time)
    print (list_number)
    
Collatz_conjecture(6) 
Collatz_conjecture(11) 
Collatz_conjecture(27) 
Collatz_conjecture(217) 